name: 'Prepare Workspace'
description: 'Sets up Nagato, applies patches, and optionally copies configuration files.'
inputs:
  target-dir:
    description: 'The directory where the target repository is located'
    required: true
  copy-to:
    description: 'Subdirectory within target-dir to copy all files from the patch directory (optional)'
    required: false
  nagato-version:
    description: 'Version of Nagato to use'
    required: false
    default: 'nightly'

runs:
  using: 'composite'
  steps:
    - name: Setup Nagato
      uses: dannycreations/nagato/.github/actions/setup-nagato@main
      with:
        version: ${{ inputs.nagato-version }}

    - name: Copy Config Files
      if: inputs.copy-to != ''
      shell: bash
      run: |
        PATCH_DIR="${{ github.workspace }}/patches/${{ inputs.target-dir }}"
        DEST_DIR="${{ inputs.target-dir }}/${{ inputs.copy-to }}"

        if [ -d "$PATCH_DIR" ]; then
          echo "Copying files from $PATCH_DIR to $DEST_DIR"
          mkdir -p "$DEST_DIR"
          cp -rv "$PATCH_DIR/." "$DEST_DIR"
        else
          echo "Source patch directory $PATCH_DIR does not exist. Skipping copy."
        fi

    - name: Apply Patches
      shell: bash
      working-directory: ${{ inputs.target-dir }}
      run: |
        PATCH_DIR="${{ github.workspace }}/patches/${{ inputs.target-dir }}"

        if [ -d "$PATCH_DIR" ]; then
          PATCHES=$(find "$PATCH_DIR" -name "*.patch" -type f | sort)

          if [ -n "$PATCHES" ]; then
            echo "Applying patches from $PATCH_DIR"
            while IFS= read -r patch; do
              nagato "$patch"
            done <<< "$PATCHES"
          else
            echo "No .patch files found in $PATCH_DIR"
          fi
        else
          echo "Patch directory $PATCH_DIR not found, skipping."
        fi
